### ISSUE TITLE
Failed to load module.

### ISSUE THREAD

**Issue by creativejaved** [rfoel/styled-content-loader#40]
I'm trying to import **StyledContentLoader** after installing package through npm. 

![Screenshot from 2020-11-10 11-14-10](https://user-images.githubusercontent.com/48195566/98632647-e5cc0200-2345-11eb-84e0-448615d096c9.png)

After import my component throws error **Module not found**

![image](https://user-images.githubusercontent.com/48195566/98632731-190e9100-2346-11eb-8d5f-e4f25332395d.png)

**Comment by rfoel** [comment]
@creativejaved  styled-components is a peer-dependency of this package, you have to install it yourself.

**Comment by creativejaved** [comment]
@rfoel Thank you for your reply. I have updated doc and requested a pull request.
